define: &BLACK 0
define: &RED 1
define: &GREEN 2
define: &YELLOW 3
define: &BLUE 4
define: &MAGENTA 5
define: &CYAN 6
define: &WHITE  7

COLOURS:
    text:
        fg: *WHITE
        bg: *BLACK
    cursor:
        fg: *BLACK
        bg: *WHITE
    status bar:
        fg: *WHITE
        bg: *BLUE